[mypy]
plugins = mypy_django_plugin.main
ignore_missing_imports = True

[mypy.plugins.django-stubs]
django_settings_module = extraction.settings

[mypy-viewer.*]
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
disallow_untyped_calls = True
disallow_subclassing_any = True
strict_equality = True
no_implicit_reexport = True

[mypy-pipeline.*]
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
disallow_untyped_calls = True
disallow_subclassing_any = True
strict_equality = True
no_implicit_reexport = True
